apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-canary
  template:
    metadata:
      labels:
        app: kafka-canary
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      securityContext:
        runAsNonRoot: true
      volumes:
        - name: certs
          projected:
            sources:
              - secret:
                  name: kafka-cluster-ca-cert
                  items:
                    - key: ca.crt
                      path: ca.crt
      containers:
        - name: kafka-canary
          image: docker.io/sebgot/kafka-canary-oauth:0.0.3
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA__CLIENTID
              value: "8c993e5f-60af-4956-9f7b-1c938c34e14f"
            - name: KAFKA__TENANTID
              value: "c90d3c25-50e1-46db-bcad-8c6628db43ae"
            - name: KAFKA__CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: canary-client-secret
                  key: secret
            - name: KAFKA__BOOTSTRAPSERVERS
              value: "kafka-kafka-external-bootstrap-ipaas-kafka-test.apps.ipaas.ocu.u.dep.no:443"
            - name: KAFKA__TOPIC
              value: "onprem.test.canary-data.add.v1"
            - name: KAFKA__SSLCALOCATION
              value: "/kafka-ca/ca.crt"
            - name: DOTNET_RUNNING_IN_CONTAINER
              value: "true"
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
          readinessProbe:
            httpGet:
              port: 8080
              path: /health/ready
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          volumeMounts:
          - name: certs
            mountPath: /kafka-ca
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-canary
  labels:
    app: kafka-canary
spec:
  selector:
    app: kafka-canary
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
